services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.2
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:7.3.2
        hostname: kafka
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
            - "29092:29092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_NUM_PARTITIONS: 3
            KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 3
            KAFKA_DEFAULT_REPLICATION_FACTOR: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_MIN_INSYNC_REPLICAS: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        healthcheck:
            test: nc -z localhost 9092 || exit -1
            start_period: 15s
            interval: 5s
            timeout: 10s
            retries: 10

    kafka-exporter:
        image: danielqsj/kafka-exporter:v1.7.0
        hostname: kafka-exporter
        container_name: kafka-exporter
        command: --kafka.server=kafka:29092
        ports:
            - 9308:9308
        depends_on:
            kafka:
              condition: service_healthy
        links:
            - kafka
            - prometheus

    postgres:
        image: postgres:14.1-alpine
        hostname: postgres
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - '5432:5432'
        volumes:
            - /var/lib/postgresql/data
#            - postgres:/var/lib/postgresql/data

    postgres-exporter:
        image: prometheuscommunity/postgres-exporter:v0.15.0
        hostname: postgres-exporter
        container_name: postgres-exporter
        ports:
            - 9187:9187
        environment:
            DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable"
        links:
            - postgres
            - prometheus

    prometheus:
        image: prom/prometheus:v2.49.1
        hostname: prometheus
        container_name: prometheus
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./config/rules.yml:/etc/prometheus/rules.yml
        ports:
            - "9090:9090"
        depends_on:
            - kafka
            - postgres

    grafana:
        image: grafana/grafana:10.2.3
        hostname: grafana
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
          - 'grafana_storage:/var/lib/grafana'

    alertmanager:
        image: prom/alertmanager:v0.26.0
        hostname: alertmanager
        container_name: alertmanager
        ports:
            - "9093:9093"
        volumes:
            - ./config/alertmanager.yml:/alertmanager/alertmanager.yml

#volumes:
#    postgres: {}
volumes:
    grafana_storage: {}
