spring:
    application:
        name: monitoring-demo
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://postgres:5432/postgres?currentSchema=demo
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                default_schema: demo
        hibernate:
            ddl-auto: validate
        generate-ddl: false
    data:
        rest:
            detection-strategy: annotated
    flyway:
        schemas: demo

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        metrics:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true

server:
    port: 9001

kafka:
    bootstrap-servers: kafka:29092
