global:
  scrape_interval:     10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: spring-boot
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['monitoring-demo-app:9001']
  - job_name: kafka
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: alertmanager
    static_configs:
      - targets: ['alertmanager:9093']
